### ISSUE TITLE
Add nested data structure to Card model

### ISSUE THREAD

**Issue by naohiro-t** [changemood/ralphs#14]
Work on this ticket after I finish creating card model

Please refer following links
[Ref.1](https://github.com/changemood/ralphs/wiki/%E3%83%8E%E3%83%BC%E3%83%88%E3%82%A2%E3%83%97%E3%83%AA%E6%A7%8B%E6%83%B3%EF%BC%88%E3%81%9D%E3%81%AE2%EF%BC%89)
[Ref.2](https://github.com/changemood/ralphs/wiki/%E6%A9%9F%E8%83%BD%E4%B8%80%E8%A6%A7#1-%E3%83%A1%E3%82%A4%E3%83%B3%E6%A9%9F%E8%83%BD)

**Comment by frankwuyue** [comment]
I found two implementations for bridge model.
**Ancestry** and **Closure tree** 

what we talked about about the bridge model is somehow like **Closure tree** but the **Ancestry** is rather simple and is more ideal if we move nodes often. So I think Ancestry is a better plan.
Please refer to the article below.

https://www.hilman.io/blog/2015/09/comparing-ancestry-and-closure_tree/

the cons of **Ancestry** is the length of ancestry column. Since right now we are using uuid of each data, so I wonder what is the length of uuid.

**Comment by frankwuyue** [comment]
**Ancestry** seems like a better plan for us right now.
So I change the tile to **Add nested data structure to Card model**

the length of uuid is 16 byte so the length of ancestry column may be a issue 
because we are limited to 255/17=15 ancestors 
but I think 15 ancestors is enough for a regular board, beside we could use text column for ancestry because the length is unlimited.

**Comment by frankwuyue** [comment]
Merged.
